### ISSUE TITLE
Provide latest version on Dockerhub

### ISSUE THREAD

**Issue by alex-voigt** [ZCube/cadvisor-docker#1]
There is already v0.36.0 out. Would be nice to get this for ARM on Dockerhub as well.

**Comment by zcube** [comment]
@alex-voigt Updated.

**Comment by alex-voigt** [comment]
Thanks for the quick response! I thought it would fix my problem with prometheus monitoring but it still doesn't expose the right metrics on my raspberry for the running state of the containers :-/
