### ISSUE TITLE
Pre-release versions

### ISSUE THREAD

**Issue by Chippi** [ZCube/cadvisor-docker#9]
Would it be possible to get images for pre-releases:

https://github.com/google/cadvisor/releases/tag/v0.40.0 Contains this change,
- Allow {memory, cpuLoad, and perf_event} metrics to be disabled by @bnutt in https://github.com/google/cadvisor/pull/2871

Which is highly benificial for me as a RPI user.

**Comment by zcube** [comment]
I'm porting to Github Actions and it will be possible once this is done. However, please understand that it is difficult to guarantee an ETA.

I'm currently working on the dev branch.

**Comment by zcube** [comment]
@Chippi done.
```
docker pull zcube/cadvisor:v0.44.1-pre
```
